name: Java Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build Application
        run: mvn clean package

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: docker build -t rahmanuddinmd17/java-docker-app:latest .

      - name: Verify Docker Image
        run: docker images

      - name: Push Docker Image
        run: docker push rahmanuddinmd17/java-docker-app:latest

      - name: Verify Push
        run: |
          echo "Docker image pushed successfully"
          echo "Image: rahmanuddinmd17/java-docker-app:latest"
